version: '3.8'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    volumes:
      - volume_db:/var/lib/mysql
    networks:
      - inception
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    restart: always
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - volume_wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_URL: ${WORDPRESS_URL}
      WORDPRESS_ADMIN_NAME: ${WORDPRESS_ADMIN_NAME}
      WORDPRESS_ADMIN_PASSWORD: ${WORDPRESS_ADMIN_PASSWORD}
      WORDPRESS_ADMIN_EMAIL: ${WORDPRESS_ADMIN_EMAIL}
      WORDPRESS_USER_NAME: ${WORDPRESS_USER_NAME}
      WORDPRESS_USER_PASSWORD: ${WORDPRESS_USER_PASSWORD}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL}

    ports:
      - "9000:9000"
    networks:
      - inception
    restart: always

networks:
  inception:
    name: inception

volumes:
  volume_db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/volume_db
  volume_wordpress:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/volume_wordpress
